# Generated by Django 3.2.23 on 2023-12-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager_app', '0002_auto_20231221_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskconfig',
            name='task_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
