# Generated by Django 3.2.23 on 2023-12-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager_app', '0003_taskconfig_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=225)),
                ('task_name', models.CharField(max_length=225)),
                ('task_status', models.CharField(max_length=225)),
            ],
        ),
    ]
