# Generated by Django 3.2.23 on 2023-12-28 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager_app', '0004_taskstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskStatus',
        ),
    ]
