# Generated by Django 3.2.23 on 2023-12-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager_app', '0005_delete_taskstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueFlagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_flag', models.BooleanField(default=False)),
            ],
        ),
    ]
