# Generated by Django 3.2.23 on 2024-01-02 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager_app', '0006_queueflagmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskconfig',
            old_name='json_data',
            new_name='task',
        ),
    ]
