# Generated by Django 3.2.23 on 2024-01-02 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager_app', '0007_rename_json_data_taskconfig_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskconfig',
            name='task_id',
        ),
    ]
