# Generated by Django 3.2.23 on 2024-01-02 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager_app', '0008_remove_taskconfig_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskconfig',
            old_name='task_name',
            new_name='name',
        ),
    ]
