# Generated by Django 3.2.23 on 2024-01-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager_app', '0010_bitmapmodels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskconfig',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
