# Generated by Django 3.2.23 on 2024-01-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager_app', '0011_alter_taskconfig_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_flag', models.BooleanField(default=False)),
                ('cancel_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='QueueFlagModel',
        ),
    ]
