# Generated by Django 3.2.23 on 2024-01-12 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager_app', '0013_alter_taskconfig_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitmapmodels',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitmapmodels',
            name='created_user',
            field=models.CharField(default='admin', max_length=50),
        ),
        migrations.AddField(
            model_name='bitmapmodels',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bitmapmodels',
            name='updated_user',
            field=models.CharField(default='admin', max_length=50),
        ),
        migrations.AddField(
            model_name='flagmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flagmodel',
            name='created_user',
            field=models.CharField(default='admin', max_length=50),
        ),
        migrations.AddField(
            model_name='flagmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='flagmodel',
            name='updated_user',
            field=models.CharField(default='admin', max_length=50),
        ),
        migrations.AddField(
            model_name='taskconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskconfig',
            name='created_user',
            field=models.CharField(default='admin', max_length=50),
        ),
        migrations.AddField(
            model_name='taskconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='taskconfig',
            name='updated_user',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
