# Generated by Django 3.2.23 on 2024-01-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager_app', '0014_auto_20240112_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskResponseModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_user', models.CharField(default='admin', max_length=50)),
                ('updated_user', models.CharField(default='admin', max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
